// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/holistic_landmarks.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HolisticPose {

  /// <summary>Holder for reflection information generated from proto/holistic_landmarks.proto</summary>
  public static partial class HolisticLandmarksReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/holistic_landmarks.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HolisticLandmarksReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5wcm90by9ob2xpc3RpY19sYW5kbWFya3MucHJvdG8SDGhvbGlzdGljUG9z",
            "ZSI/CghMYW5kbWFyaxIJCgF4GAIgASgCEgkKAXkYAyABKAISCQoBehgEIAEo",
            "AhISCgpjb25maWRlbmNlGAYgASgCIjgKDExhbmRtYXJrTGlzdBIoCghsYW5k",
            "bWFyaxgBIAMoCzIWLmhvbGlzdGljUG9zZS5MYW5kbWFyayLoAQoRSG9saXN0",
            "aWNMYW5kbWFya3MSMQoNcG9zZUxhbmRtYXJrcxgBIAEoCzIaLmhvbGlzdGlj",
            "UG9zZS5MYW5kbWFya0xpc3QSNQoRbGVmdEhhbmRMYW5kbWFya3MYAiABKAsy",
            "Gi5ob2xpc3RpY1Bvc2UuTGFuZG1hcmtMaXN0EjYKEnJpZ2h0SGFuZExhbmRt",
            "YXJrcxgDIAEoCzIaLmhvbGlzdGljUG9zZS5MYW5kbWFya0xpc3QSMQoNZmFj",
            "ZUxhbmRtYXJrcxgEIAEoCzIaLmhvbGlzdGljUG9zZS5MYW5kbWFya0xpc3Qq",
            "kgQKDFBvc2VMYW5kbWFyaxIICgRub3NlEAASEAoMbGVmdEV5ZUlubmVyEAES",
            "CwoHbGVmdEV5ZRACEhAKDGxlZnRFeWVPdXRlchADEhEKDXJpZ2h0RXllSW5u",
            "ZXIQBBIMCghyaWdodEV5ZRAFEhEKDXJpZ2h0RXllT3V0ZXIQBhILCgdsZWZ0",
            "RWFyEAcSDAoIcmlnaHRFYXIQCBINCgltb3V0aExlZnQQCRIOCgptb3V0aFJp",
            "Z2h0EAoSEAoMbGVmdFNob3VsZGVyEAsSEQoNcmlnaHRTaG91bGRlchAMEg0K",
            "CWxlZnRFbGJvdxANEg4KCnJpZ2h0RWxib3cQDhINCglsZWZ0V3Jpc3QQDxIO",
            "CgpyaWdodFdyaXN0EBASDQoJbGVmdFBpbmt5EBESDgoKcmlnaHRQaW5reRAS",
            "Eg0KCWxlZnRJbmRleBATEg4KCnJpZ2h0SW5kZXgQFBINCglsZWZ0VGh1bWIQ",
            "FRIOCgpyaWdodFRodW1iEBYSCwoHbGVmdEhpcBAXEgwKCHJpZ2h0SGlwEBgS",
            "DAoIbGVmdEtuZWUQGRINCglyaWdodEtuZWUQGhINCglsZWZ0QW5rbGUQGxIO",
            "CgpyaWdodEFua2xlEBwSDAoIbGVmdEhlZWwQHRINCglyaWdodEhlZWwQHhIR",
            "Cg1sZWZ0Rm9vdEluZGV4EB8SEgoOcmlnaHRGb290SW5kZXgQICr4AgoMSGFu",
            "ZExhbmRtYXJrEgkKBXdyaXN0EAASDAoIdGh1bWJDTUMQARIMCgh0aHVtYk1D",
            "UBACEgsKB3RodW1iSVAQAxIMCgh0aHVtYlRJUBAEEhIKDmluZGV4RmluZ2Vy",
            "TUNQEAUSEgoOaW5kZXhGaW5nZXJQSVAQBhISCg5pbmRleEZpbmdlckRJUBAH",
            "EhIKDmluZGV4RmluZ2VyVElQEAgSEwoPbWlkZGxlRmluZ2VyTUNQEAkSEwoP",
            "bWlkZGxlRmluZ2VyUElQEAoSEwoPbWlkZGxlRmluZ2VyRElQEAsSEwoPbWlk",
            "ZGxlRmluZ2VyVElQEAwSEQoNcmluZ0Zpbmdlck1DUBANEhEKDXJpbmdGaW5n",
            "ZXJQSVAQDhIRCg1yaW5nRmluZ2VyRElQEA8SEQoNcmluZ0ZpbmdlclRJUBAQ",
            "EgwKCHBpbmt5TUNQEBESDAoIcGlua3lQSVAQEhIMCghwaW5reURJUBATEgwK",
            "CHBpbmt5VElQEBRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::HolisticPose.PoseLandmark), typeof(global::HolisticPose.HandLandmark), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HolisticPose.Landmark), global::HolisticPose.Landmark.Parser, new[]{ "X", "Y", "Z", "Confidence" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HolisticPose.LandmarkList), global::HolisticPose.LandmarkList.Parser, new[]{ "Landmark" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HolisticPose.HolisticLandmarks), global::HolisticPose.HolisticLandmarks.Parser, new[]{ "PoseLandmarks", "LeftHandLandmarks", "RightHandLandmarks", "FaceLandmarks" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PoseLandmark {
    [pbr::OriginalName("nose")] Nose = 0,
    [pbr::OriginalName("leftEyeInner")] LeftEyeInner = 1,
    [pbr::OriginalName("leftEye")] LeftEye = 2,
    [pbr::OriginalName("leftEyeOuter")] LeftEyeOuter = 3,
    [pbr::OriginalName("rightEyeInner")] RightEyeInner = 4,
    [pbr::OriginalName("rightEye")] RightEye = 5,
    [pbr::OriginalName("rightEyeOuter")] RightEyeOuter = 6,
    [pbr::OriginalName("leftEar")] LeftEar = 7,
    [pbr::OriginalName("rightEar")] RightEar = 8,
    [pbr::OriginalName("mouthLeft")] MouthLeft = 9,
    [pbr::OriginalName("mouthRight")] MouthRight = 10,
    [pbr::OriginalName("leftShoulder")] LeftShoulder = 11,
    [pbr::OriginalName("rightShoulder")] RightShoulder = 12,
    [pbr::OriginalName("leftElbow")] LeftElbow = 13,
    [pbr::OriginalName("rightElbow")] RightElbow = 14,
    [pbr::OriginalName("leftWrist")] LeftWrist = 15,
    [pbr::OriginalName("rightWrist")] RightWrist = 16,
    [pbr::OriginalName("leftPinky")] LeftPinky = 17,
    [pbr::OriginalName("rightPinky")] RightPinky = 18,
    [pbr::OriginalName("leftIndex")] LeftIndex = 19,
    [pbr::OriginalName("rightIndex")] RightIndex = 20,
    [pbr::OriginalName("leftThumb")] LeftThumb = 21,
    [pbr::OriginalName("rightThumb")] RightThumb = 22,
    [pbr::OriginalName("leftHip")] LeftHip = 23,
    [pbr::OriginalName("rightHip")] RightHip = 24,
    [pbr::OriginalName("leftKnee")] LeftKnee = 25,
    [pbr::OriginalName("rightKnee")] RightKnee = 26,
    [pbr::OriginalName("leftAnkle")] LeftAnkle = 27,
    [pbr::OriginalName("rightAnkle")] RightAnkle = 28,
    [pbr::OriginalName("leftHeel")] LeftHeel = 29,
    [pbr::OriginalName("rightHeel")] RightHeel = 30,
    [pbr::OriginalName("leftFootIndex")] LeftFootIndex = 31,
    [pbr::OriginalName("rightFootIndex")] RightFootIndex = 32,
  }

  public enum HandLandmark {
    [pbr::OriginalName("wrist")] Wrist = 0,
    [pbr::OriginalName("thumbCMC")] ThumbCmc = 1,
    [pbr::OriginalName("thumbMCP")] ThumbMcp = 2,
    [pbr::OriginalName("thumbIP")] ThumbIp = 3,
    [pbr::OriginalName("thumbTIP")] ThumbTip = 4,
    [pbr::OriginalName("indexFingerMCP")] IndexFingerMcp = 5,
    [pbr::OriginalName("indexFingerPIP")] IndexFingerPip = 6,
    [pbr::OriginalName("indexFingerDIP")] IndexFingerDip = 7,
    [pbr::OriginalName("indexFingerTIP")] IndexFingerTip = 8,
    [pbr::OriginalName("middleFingerMCP")] MiddleFingerMcp = 9,
    [pbr::OriginalName("middleFingerPIP")] MiddleFingerPip = 10,
    [pbr::OriginalName("middleFingerDIP")] MiddleFingerDip = 11,
    [pbr::OriginalName("middleFingerTIP")] MiddleFingerTip = 12,
    [pbr::OriginalName("ringFingerMCP")] RingFingerMcp = 13,
    [pbr::OriginalName("ringFingerPIP")] RingFingerPip = 14,
    [pbr::OriginalName("ringFingerDIP")] RingFingerDip = 15,
    [pbr::OriginalName("ringFingerTIP")] RingFingerTip = 16,
    [pbr::OriginalName("pinkyMCP")] PinkyMcp = 17,
    [pbr::OriginalName("pinkyPIP")] PinkyPip = 18,
    [pbr::OriginalName("pinkyDIP")] PinkyDip = 19,
    [pbr::OriginalName("pinkyTIP")] PinkyTip = 20,
  }

  #endregion

  #region Messages
  public sealed partial class Landmark : pb::IMessage<Landmark>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Landmark> _parser = new pb::MessageParser<Landmark>(() => new Landmark());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Landmark> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HolisticPose.HolisticLandmarksReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Landmark() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Landmark(Landmark other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      confidence_ = other.confidence_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Landmark Clone() {
      return new Landmark(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 2;
    private float x_;
    /// <summary>
    /// string name = 1;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 3;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 4;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    /// <summary>Field number for the "confidence" field.</summary>
    public const int ConfidenceFieldNumber = 6;
    private float confidence_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Confidence {
      get { return confidence_; }
      set {
        confidence_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Landmark);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Landmark other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Confidence, other.Confidence)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (Confidence != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Confidence);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (X != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Z);
      }
      if (Confidence != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Confidence);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (X != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Z);
      }
      if (Confidence != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Confidence);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Z != 0F) {
        size += 1 + 4;
      }
      if (Confidence != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Landmark other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      if (other.Confidence != 0F) {
        Confidence = other.Confidence;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 21: {
            X = input.ReadFloat();
            break;
          }
          case 29: {
            Y = input.ReadFloat();
            break;
          }
          case 37: {
            Z = input.ReadFloat();
            break;
          }
          case 53: {
            Confidence = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 21: {
            X = input.ReadFloat();
            break;
          }
          case 29: {
            Y = input.ReadFloat();
            break;
          }
          case 37: {
            Z = input.ReadFloat();
            break;
          }
          case 53: {
            Confidence = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class LandmarkList : pb::IMessage<LandmarkList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LandmarkList> _parser = new pb::MessageParser<LandmarkList>(() => new LandmarkList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LandmarkList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HolisticPose.HolisticLandmarksReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LandmarkList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LandmarkList(LandmarkList other) : this() {
      landmark_ = other.landmark_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LandmarkList Clone() {
      return new LandmarkList(this);
    }

    /// <summary>Field number for the "landmark" field.</summary>
    public const int LandmarkFieldNumber = 1;
    private static readonly pb::FieldCodec<global::HolisticPose.Landmark> _repeated_landmark_codec
        = pb::FieldCodec.ForMessage(10, global::HolisticPose.Landmark.Parser);
    private readonly pbc::RepeatedField<global::HolisticPose.Landmark> landmark_ = new pbc::RepeatedField<global::HolisticPose.Landmark>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::HolisticPose.Landmark> Landmark {
      get { return landmark_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LandmarkList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LandmarkList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!landmark_.Equals(other.landmark_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= landmark_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      landmark_.WriteTo(output, _repeated_landmark_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      landmark_.WriteTo(ref output, _repeated_landmark_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += landmark_.CalculateSize(_repeated_landmark_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LandmarkList other) {
      if (other == null) {
        return;
      }
      landmark_.Add(other.landmark_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            landmark_.AddEntriesFrom(input, _repeated_landmark_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            landmark_.AddEntriesFrom(ref input, _repeated_landmark_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class HolisticLandmarks : pb::IMessage<HolisticLandmarks>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HolisticLandmarks> _parser = new pb::MessageParser<HolisticLandmarks>(() => new HolisticLandmarks());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HolisticLandmarks> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HolisticPose.HolisticLandmarksReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HolisticLandmarks() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HolisticLandmarks(HolisticLandmarks other) : this() {
      poseLandmarks_ = other.poseLandmarks_ != null ? other.poseLandmarks_.Clone() : null;
      leftHandLandmarks_ = other.leftHandLandmarks_ != null ? other.leftHandLandmarks_.Clone() : null;
      rightHandLandmarks_ = other.rightHandLandmarks_ != null ? other.rightHandLandmarks_.Clone() : null;
      faceLandmarks_ = other.faceLandmarks_ != null ? other.faceLandmarks_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HolisticLandmarks Clone() {
      return new HolisticLandmarks(this);
    }

    /// <summary>Field number for the "poseLandmarks" field.</summary>
    public const int PoseLandmarksFieldNumber = 1;
    private global::HolisticPose.LandmarkList poseLandmarks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HolisticPose.LandmarkList PoseLandmarks {
      get { return poseLandmarks_; }
      set {
        poseLandmarks_ = value;
      }
    }

    /// <summary>Field number for the "leftHandLandmarks" field.</summary>
    public const int LeftHandLandmarksFieldNumber = 2;
    private global::HolisticPose.LandmarkList leftHandLandmarks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HolisticPose.LandmarkList LeftHandLandmarks {
      get { return leftHandLandmarks_; }
      set {
        leftHandLandmarks_ = value;
      }
    }

    /// <summary>Field number for the "rightHandLandmarks" field.</summary>
    public const int RightHandLandmarksFieldNumber = 3;
    private global::HolisticPose.LandmarkList rightHandLandmarks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HolisticPose.LandmarkList RightHandLandmarks {
      get { return rightHandLandmarks_; }
      set {
        rightHandLandmarks_ = value;
      }
    }

    /// <summary>Field number for the "faceLandmarks" field.</summary>
    public const int FaceLandmarksFieldNumber = 4;
    private global::HolisticPose.LandmarkList faceLandmarks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::HolisticPose.LandmarkList FaceLandmarks {
      get { return faceLandmarks_; }
      set {
        faceLandmarks_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HolisticLandmarks);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HolisticLandmarks other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PoseLandmarks, other.PoseLandmarks)) return false;
      if (!object.Equals(LeftHandLandmarks, other.LeftHandLandmarks)) return false;
      if (!object.Equals(RightHandLandmarks, other.RightHandLandmarks)) return false;
      if (!object.Equals(FaceLandmarks, other.FaceLandmarks)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (poseLandmarks_ != null) hash ^= PoseLandmarks.GetHashCode();
      if (leftHandLandmarks_ != null) hash ^= LeftHandLandmarks.GetHashCode();
      if (rightHandLandmarks_ != null) hash ^= RightHandLandmarks.GetHashCode();
      if (faceLandmarks_ != null) hash ^= FaceLandmarks.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (poseLandmarks_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PoseLandmarks);
      }
      if (leftHandLandmarks_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LeftHandLandmarks);
      }
      if (rightHandLandmarks_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RightHandLandmarks);
      }
      if (faceLandmarks_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(FaceLandmarks);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (poseLandmarks_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PoseLandmarks);
      }
      if (leftHandLandmarks_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LeftHandLandmarks);
      }
      if (rightHandLandmarks_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RightHandLandmarks);
      }
      if (faceLandmarks_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(FaceLandmarks);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (poseLandmarks_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PoseLandmarks);
      }
      if (leftHandLandmarks_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeftHandLandmarks);
      }
      if (rightHandLandmarks_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RightHandLandmarks);
      }
      if (faceLandmarks_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FaceLandmarks);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HolisticLandmarks other) {
      if (other == null) {
        return;
      }
      if (other.poseLandmarks_ != null) {
        if (poseLandmarks_ == null) {
          PoseLandmarks = new global::HolisticPose.LandmarkList();
        }
        PoseLandmarks.MergeFrom(other.PoseLandmarks);
      }
      if (other.leftHandLandmarks_ != null) {
        if (leftHandLandmarks_ == null) {
          LeftHandLandmarks = new global::HolisticPose.LandmarkList();
        }
        LeftHandLandmarks.MergeFrom(other.LeftHandLandmarks);
      }
      if (other.rightHandLandmarks_ != null) {
        if (rightHandLandmarks_ == null) {
          RightHandLandmarks = new global::HolisticPose.LandmarkList();
        }
        RightHandLandmarks.MergeFrom(other.RightHandLandmarks);
      }
      if (other.faceLandmarks_ != null) {
        if (faceLandmarks_ == null) {
          FaceLandmarks = new global::HolisticPose.LandmarkList();
        }
        FaceLandmarks.MergeFrom(other.FaceLandmarks);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (poseLandmarks_ == null) {
              PoseLandmarks = new global::HolisticPose.LandmarkList();
            }
            input.ReadMessage(PoseLandmarks);
            break;
          }
          case 18: {
            if (leftHandLandmarks_ == null) {
              LeftHandLandmarks = new global::HolisticPose.LandmarkList();
            }
            input.ReadMessage(LeftHandLandmarks);
            break;
          }
          case 26: {
            if (rightHandLandmarks_ == null) {
              RightHandLandmarks = new global::HolisticPose.LandmarkList();
            }
            input.ReadMessage(RightHandLandmarks);
            break;
          }
          case 34: {
            if (faceLandmarks_ == null) {
              FaceLandmarks = new global::HolisticPose.LandmarkList();
            }
            input.ReadMessage(FaceLandmarks);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (poseLandmarks_ == null) {
              PoseLandmarks = new global::HolisticPose.LandmarkList();
            }
            input.ReadMessage(PoseLandmarks);
            break;
          }
          case 18: {
            if (leftHandLandmarks_ == null) {
              LeftHandLandmarks = new global::HolisticPose.LandmarkList();
            }
            input.ReadMessage(LeftHandLandmarks);
            break;
          }
          case 26: {
            if (rightHandLandmarks_ == null) {
              RightHandLandmarks = new global::HolisticPose.LandmarkList();
            }
            input.ReadMessage(RightHandLandmarks);
            break;
          }
          case 34: {
            if (faceLandmarks_ == null) {
              FaceLandmarks = new global::HolisticPose.LandmarkList();
            }
            input.ReadMessage(FaceLandmarks);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
