name: Prepare Release
description: Copy Samples to package

runs:
  using: composite
  steps:
    - name: Copy Samples to package
      shell: bash
      run: |
        mkdir -p Assets/VioletSolver/Samples~
        # Copy only script files (without .meta and asmdef)
        rsync -av --exclude='*.meta' --exclude='*.asmdef' Assets/Development/Samples/Scripts/ Assets/VioletSolver/Samples~/

    - name: Verify no .meta files copied
      shell: bash
      run: |
        echo "=== Checking for .meta files in Samples~ ==="
        META_COUNT=$(find Assets/VioletSolver/Samples~ -name "*.meta" | wc -l)
        if [ "$META_COUNT" -gt 0 ]; then
          echo "ERROR: Found $META_COUNT .meta files!"
          find Assets/VioletSolver/Samples~ -name "*.meta"
          exit 1
        fi
        echo "OK: No .meta files found"
        echo ""
        echo "=== Files in Samples~ ==="
        find Assets/VioletSolver/Samples~ -type f | head -50
