// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: avatar_animation_log.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace VioletSolver.Recorder {

  /// <summary>Holder for reflection information generated from avatar_animation_log.proto</summary>
  public static partial class AvatarAnimationLogReflection {

    #region Descriptor
    /// <summary>File descriptor for avatar_animation_log.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AvatarAnimationLogReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChphdmF0YXJfYW5pbWF0aW9uX2xvZy5wcm90bxIVdmlvbGV0U29sdmVyLnJl",
            "Y29yZGVyIlQKCUxvZ0hlYWRlchIaChJsb2dfc2NoZW1hX3ZlcnNpb24YASAB",
            "KAkSEwoLYXZhdGFyX25hbWUYAiABKAkSFgoOYXZhdGFyX3ZlcnNpb24YAyAB",
            "KAkirAEKDExvZ0ZyYW1lRGF0YRIUCgx0aW1lc3RhbXBfbXMYASABKAESFAoM",
            "ZnJhbWVfbnVtYmVyGAIgASgNEjYKC2F2YXRhcl9wb3NlGAMgASgLMiEudmlv",
            "bGV0U29sdmVyLnJlY29yZGVyLkF2YXRhclBvc2USOAoMZGV2aWNlX3VzYWdl",
            "GAQgASgLMiIudmlvbGV0U29sdmVyLnJlY29yZGVyLkRldmljZVVzYWdlIjYK",
            "CFJvdGF0aW9uEgkKAXgYASABKAISCQoBeRgCIAEoAhIJCgF6GAMgASgCEgkK",
            "AXcYBCABKAIiKwoIUG9zaXRpb24SCQoBeBgBIAEoAhIJCgF5GAIgASgCEgkK",
            "AXoYAyABKAIirQEKDUJvbmVUcmFuc2Zvcm0SFwoPYm9uZV90eXBlX3ZhbHVl",
            "GAEgASgFEhEKCWJvbmVfbmFtZRgCIAEoCRI3Cg5sb2NhbF9yb3RhdGlvbhgD",
            "IAEoCzIfLnZpb2xldFNvbHZlci5yZWNvcmRlci5Sb3RhdGlvbhI3Cg5sb2Nh",
            "bF9wb3NpdGlvbhgEIAEoCzIfLnZpb2xldFNvbHZlci5yZWNvcmRlci5Qb3Np",
            "dGlvbiKEAQoKQXZhdGFyUG9zZRI9Cg9ib25lX3RyYW5zZm9ybXMYASADKAsy",
            "JC52aW9sZXRTb2x2ZXIucmVjb3JkZXIuQm9uZVRyYW5zZm9ybRI3CgtibGVu",
            "ZHNoYXBlcxgCIAEoCzIiLnZpb2xldFNvbHZlci5yZWNvcmRlci5CbGVuZHNo",
            "YXBlcyK7CAoLQmxlbmRzaGFwZXMSDwoHd2VpZ2h0cxgBIAMoAiKaCAoQQmxl",
            "bmRzaGFwZXNJbmRleBIMCghfbmV1dHJhbBAAEhAKDGJyb3dEb3duTGVmdBAB",
            "EhEKDWJyb3dEb3duUmlnaHQQAhIPCgticm93SW5uZXJVcBADEhMKD2Jyb3dP",
            "dXRlclVwTGVmdBAEEhQKEGJyb3dPdXRlclVwUmlnaHQQBRINCgljaGVla1B1",
            "ZmYQBhITCg9jaGVla1NxdWludExlZnQQBxIUChBjaGVla1NxdWludFJpZ2h0",
            "EAgSEAoMZXllQmxpbmtMZWZ0EAkSEQoNZXllQmxpbmtSaWdodBAKEhMKD2V5",
            "ZUxvb2tEb3duTGVmdBALEhQKEGV5ZUxvb2tEb3duUmlnaHQQDBIRCg1leWVM",
            "b29rSW5MZWZ0EA0SEgoOZXllTG9va0luUmlnaHQQDhISCg5leWVMb29rT3V0",
            "TGVmdBAPEhMKD2V5ZUxvb2tPdXRSaWdodBAQEhEKDWV5ZUxvb2tVcExlZnQQ",
            "ERISCg5leWVMb29rVXBSaWdodBASEhEKDWV5ZVNxdWludExlZnQQExISCg5l",
            "eWVTcXVpbnRSaWdodBAUEg8KC2V5ZVdpZGVMZWZ0EBUSEAoMZXllV2lkZVJp",
            "Z2h0EBYSDgoKamF3Rm9yd2FyZBAXEgsKB2phd0xlZnQQGBILCgdqYXdPcGVu",
            "EBkSDAoIamF3UmlnaHQQGhIOCgptb3V0aENsb3NlEBsSEwoPbW91dGhEaW1w",
            "bGVMZWZ0EBwSFAoQbW91dGhEaW1wbGVSaWdodBAdEhIKDm1vdXRoRnJvd25M",
            "ZWZ0EB4SEwoPbW91dGhGcm93blJpZ2h0EB8SDwoLbW91dGhGdW5uZWwQIBIN",
            "Cgltb3V0aExlZnQQIRIWChJtb3V0aExvd2VyRG93bkxlZnQQIhIXChNtb3V0",
            "aExvd2VyRG93blJpZ2h0ECMSEgoObW91dGhQcmVzc0xlZnQQJBITCg9tb3V0",
            "aFByZXNzUmlnaHQQJRIPCgttb3V0aFB1Y2tlchAmEg4KCm1vdXRoUmlnaHQQ",
            "JxISCg5tb3V0aFJvbGxMb3dlchAoEhIKDm1vdXRoUm9sbFVwcGVyECkSEwoP",
            "bW91dGhTaHJ1Z0xvd2VyECoSEwoPbW91dGhTaHJ1Z1VwcGVyECsSEgoObW91",
            "dGhTbWlsZUxlZnQQLBITCg9tb3V0aFNtaWxlUmlnaHQQLRIUChBtb3V0aFN0",
            "cmV0Y2hMZWZ0EC4SFQoRbW91dGhTdHJldGNoUmlnaHQQLxIUChBtb3V0aFVw",
            "cGVyVXBMZWZ0EDASFQoRbW91dGhVcHBlclVwUmlnaHQQMRIRCg1ub3NlU25l",
            "ZXJMZWZ0EDISEgoObm9zZVNuZWVyUmlnaHQQMxINCgl0b25ndWVPdXQQNBIK",
            "CgZsZW5ndGgQNSJACgtEZXZpY2VVc2FnZRIWCg5pc19tb3VzZV91c2luZxgB",
            "IAEoCBIZChFpc19rZXlib2FyZF91c2luZxgCIAEoCGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::VioletSolver.Recorder.LogHeader), global::VioletSolver.Recorder.LogHeader.Parser, new[]{ "LogSchemaVersion", "AvatarName", "AvatarVersion" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VioletSolver.Recorder.LogFrameData), global::VioletSolver.Recorder.LogFrameData.Parser, new[]{ "TimestampMs", "FrameNumber", "AvatarPose", "DeviceUsage" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VioletSolver.Recorder.Rotation), global::VioletSolver.Recorder.Rotation.Parser, new[]{ "X", "Y", "Z", "W" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VioletSolver.Recorder.Position), global::VioletSolver.Recorder.Position.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VioletSolver.Recorder.BoneTransform), global::VioletSolver.Recorder.BoneTransform.Parser, new[]{ "BoneTypeValue", "BoneName", "LocalRotation", "LocalPosition" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VioletSolver.Recorder.AvatarPose), global::VioletSolver.Recorder.AvatarPose.Parser, new[]{ "BoneTransforms", "Blendshapes" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VioletSolver.Recorder.Blendshapes), global::VioletSolver.Recorder.Blendshapes.Parser, new[]{ "Weights" }, null, new[]{ typeof(global::VioletSolver.Recorder.Blendshapes.Types.BlendshapesIndex) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::VioletSolver.Recorder.DeviceUsage), global::VioletSolver.Recorder.DeviceUsage.Parser, new[]{ "IsMouseUsing", "IsKeyboardUsing" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// recorded once in head of the log file
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LogHeader : pb::IMessage<LogHeader>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LogHeader> _parser = new pb::MessageParser<LogHeader>(() => new LogHeader());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LogHeader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VioletSolver.Recorder.AvatarAnimationLogReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogHeader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogHeader(LogHeader other) : this() {
      logSchemaVersion_ = other.logSchemaVersion_;
      avatarName_ = other.avatarName_;
      avatarVersion_ = other.avatarVersion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogHeader Clone() {
      return new LogHeader(this);
    }

    /// <summary>Field number for the "log_schema_version" field.</summary>
    public const int LogSchemaVersionFieldNumber = 1;
    private string logSchemaVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LogSchemaVersion {
      get { return logSchemaVersion_; }
      set {
        logSchemaVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar_name" field.</summary>
    public const int AvatarNameFieldNumber = 2;
    private string avatarName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AvatarName {
      get { return avatarName_; }
      set {
        avatarName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "avatar_version" field.</summary>
    public const int AvatarVersionFieldNumber = 3;
    private string avatarVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AvatarVersion {
      get { return avatarVersion_; }
      set {
        avatarVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LogHeader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LogHeader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LogSchemaVersion != other.LogSchemaVersion) return false;
      if (AvatarName != other.AvatarName) return false;
      if (AvatarVersion != other.AvatarVersion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LogSchemaVersion.Length != 0) hash ^= LogSchemaVersion.GetHashCode();
      if (AvatarName.Length != 0) hash ^= AvatarName.GetHashCode();
      if (AvatarVersion.Length != 0) hash ^= AvatarVersion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LogSchemaVersion.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LogSchemaVersion);
      }
      if (AvatarName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AvatarName);
      }
      if (AvatarVersion.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AvatarVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LogSchemaVersion.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LogSchemaVersion);
      }
      if (AvatarName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AvatarName);
      }
      if (AvatarVersion.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AvatarVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LogSchemaVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LogSchemaVersion);
      }
      if (AvatarName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AvatarName);
      }
      if (AvatarVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AvatarVersion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LogHeader other) {
      if (other == null) {
        return;
      }
      if (other.LogSchemaVersion.Length != 0) {
        LogSchemaVersion = other.LogSchemaVersion;
      }
      if (other.AvatarName.Length != 0) {
        AvatarName = other.AvatarName;
      }
      if (other.AvatarVersion.Length != 0) {
        AvatarVersion = other.AvatarVersion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LogSchemaVersion = input.ReadString();
            break;
          }
          case 18: {
            AvatarName = input.ReadString();
            break;
          }
          case 26: {
            AvatarVersion = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            LogSchemaVersion = input.ReadString();
            break;
          }
          case 18: {
            AvatarName = input.ReadString();
            break;
          }
          case 26: {
            AvatarVersion = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// recorded in each of frame
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LogFrameData : pb::IMessage<LogFrameData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LogFrameData> _parser = new pb::MessageParser<LogFrameData>(() => new LogFrameData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LogFrameData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VioletSolver.Recorder.AvatarAnimationLogReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogFrameData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogFrameData(LogFrameData other) : this() {
      timestampMs_ = other.timestampMs_;
      frameNumber_ = other.frameNumber_;
      avatarPose_ = other.avatarPose_ != null ? other.avatarPose_.Clone() : null;
      deviceUsage_ = other.deviceUsage_ != null ? other.deviceUsage_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogFrameData Clone() {
      return new LogFrameData(this);
    }

    /// <summary>Field number for the "timestamp_ms" field.</summary>
    public const int TimestampMsFieldNumber = 1;
    private double timestampMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double TimestampMs {
      get { return timestampMs_; }
      set {
        timestampMs_ = value;
      }
    }

    /// <summary>Field number for the "frame_number" field.</summary>
    public const int FrameNumberFieldNumber = 2;
    private uint frameNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FrameNumber {
      get { return frameNumber_; }
      set {
        frameNumber_ = value;
      }
    }

    /// <summary>Field number for the "avatar_pose" field.</summary>
    public const int AvatarPoseFieldNumber = 3;
    private global::VioletSolver.Recorder.AvatarPose avatarPose_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VioletSolver.Recorder.AvatarPose AvatarPose {
      get { return avatarPose_; }
      set {
        avatarPose_ = value;
      }
    }

    /// <summary>Field number for the "device_usage" field.</summary>
    public const int DeviceUsageFieldNumber = 4;
    private global::VioletSolver.Recorder.DeviceUsage deviceUsage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VioletSolver.Recorder.DeviceUsage DeviceUsage {
      get { return deviceUsage_; }
      set {
        deviceUsage_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LogFrameData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LogFrameData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(TimestampMs, other.TimestampMs)) return false;
      if (FrameNumber != other.FrameNumber) return false;
      if (!object.Equals(AvatarPose, other.AvatarPose)) return false;
      if (!object.Equals(DeviceUsage, other.DeviceUsage)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TimestampMs != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(TimestampMs);
      if (FrameNumber != 0) hash ^= FrameNumber.GetHashCode();
      if (avatarPose_ != null) hash ^= AvatarPose.GetHashCode();
      if (deviceUsage_ != null) hash ^= DeviceUsage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TimestampMs != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(TimestampMs);
      }
      if (FrameNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(FrameNumber);
      }
      if (avatarPose_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AvatarPose);
      }
      if (deviceUsage_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(DeviceUsage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TimestampMs != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(TimestampMs);
      }
      if (FrameNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(FrameNumber);
      }
      if (avatarPose_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AvatarPose);
      }
      if (deviceUsage_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(DeviceUsage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TimestampMs != 0D) {
        size += 1 + 8;
      }
      if (FrameNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FrameNumber);
      }
      if (avatarPose_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AvatarPose);
      }
      if (deviceUsage_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeviceUsage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LogFrameData other) {
      if (other == null) {
        return;
      }
      if (other.TimestampMs != 0D) {
        TimestampMs = other.TimestampMs;
      }
      if (other.FrameNumber != 0) {
        FrameNumber = other.FrameNumber;
      }
      if (other.avatarPose_ != null) {
        if (avatarPose_ == null) {
          AvatarPose = new global::VioletSolver.Recorder.AvatarPose();
        }
        AvatarPose.MergeFrom(other.AvatarPose);
      }
      if (other.deviceUsage_ != null) {
        if (deviceUsage_ == null) {
          DeviceUsage = new global::VioletSolver.Recorder.DeviceUsage();
        }
        DeviceUsage.MergeFrom(other.DeviceUsage);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            TimestampMs = input.ReadDouble();
            break;
          }
          case 16: {
            FrameNumber = input.ReadUInt32();
            break;
          }
          case 26: {
            if (avatarPose_ == null) {
              AvatarPose = new global::VioletSolver.Recorder.AvatarPose();
            }
            input.ReadMessage(AvatarPose);
            break;
          }
          case 34: {
            if (deviceUsage_ == null) {
              DeviceUsage = new global::VioletSolver.Recorder.DeviceUsage();
            }
            input.ReadMessage(DeviceUsage);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            TimestampMs = input.ReadDouble();
            break;
          }
          case 16: {
            FrameNumber = input.ReadUInt32();
            break;
          }
          case 26: {
            if (avatarPose_ == null) {
              AvatarPose = new global::VioletSolver.Recorder.AvatarPose();
            }
            input.ReadMessage(AvatarPose);
            break;
          }
          case 34: {
            if (deviceUsage_ == null) {
              DeviceUsage = new global::VioletSolver.Recorder.DeviceUsage();
            }
            input.ReadMessage(DeviceUsage);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Rotation : pb::IMessage<Rotation>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Rotation> _parser = new pb::MessageParser<Rotation>(() => new Rotation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Rotation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VioletSolver.Recorder.AvatarAnimationLogReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Rotation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Rotation(Rotation other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      w_ = other.w_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Rotation Clone() {
      return new Rotation(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private float x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    /// <summary>Field number for the "w" field.</summary>
    public const int WFieldNumber = 4;
    private float w_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float W {
      get { return w_; }
      set {
        w_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Rotation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Rotation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(W, other.W)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (W != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(W);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (W != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(W);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (W != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(W);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Z != 0F) {
        size += 1 + 4;
      }
      if (W != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Rotation other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      if (other.W != 0F) {
        W = other.W;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
          case 37: {
            W = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
          case 37: {
            W = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Position : pb::IMessage<Position>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Position> _parser = new pb::MessageParser<Position>(() => new Position());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Position> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VioletSolver.Recorder.AvatarAnimationLogReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Position() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Position(Position other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Position Clone() {
      return new Position(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private float x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Position);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Position other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Z != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Position other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BoneTransform : pb::IMessage<BoneTransform>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BoneTransform> _parser = new pb::MessageParser<BoneTransform>(() => new BoneTransform());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BoneTransform> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VioletSolver.Recorder.AvatarAnimationLogReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BoneTransform() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BoneTransform(BoneTransform other) : this() {
      boneTypeValue_ = other.boneTypeValue_;
      boneName_ = other.boneName_;
      localRotation_ = other.localRotation_ != null ? other.localRotation_.Clone() : null;
      localPosition_ = other.localPosition_ != null ? other.localPosition_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BoneTransform Clone() {
      return new BoneTransform(this);
    }

    /// <summary>Field number for the "bone_type_value" field.</summary>
    public const int BoneTypeValueFieldNumber = 1;
    private int boneTypeValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BoneTypeValue {
      get { return boneTypeValue_; }
      set {
        boneTypeValue_ = value;
      }
    }

    /// <summary>Field number for the "bone_name" field.</summary>
    public const int BoneNameFieldNumber = 2;
    private string boneName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BoneName {
      get { return boneName_; }
      set {
        boneName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "local_rotation" field.</summary>
    public const int LocalRotationFieldNumber = 3;
    private global::VioletSolver.Recorder.Rotation localRotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VioletSolver.Recorder.Rotation LocalRotation {
      get { return localRotation_; }
      set {
        localRotation_ = value;
      }
    }

    /// <summary>Field number for the "local_position" field.</summary>
    public const int LocalPositionFieldNumber = 4;
    private global::VioletSolver.Recorder.Position localPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VioletSolver.Recorder.Position LocalPosition {
      get { return localPosition_; }
      set {
        localPosition_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BoneTransform);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BoneTransform other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BoneTypeValue != other.BoneTypeValue) return false;
      if (BoneName != other.BoneName) return false;
      if (!object.Equals(LocalRotation, other.LocalRotation)) return false;
      if (!object.Equals(LocalPosition, other.LocalPosition)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BoneTypeValue != 0) hash ^= BoneTypeValue.GetHashCode();
      if (BoneName.Length != 0) hash ^= BoneName.GetHashCode();
      if (localRotation_ != null) hash ^= LocalRotation.GetHashCode();
      if (localPosition_ != null) hash ^= LocalPosition.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BoneTypeValue != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BoneTypeValue);
      }
      if (BoneName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BoneName);
      }
      if (localRotation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(LocalRotation);
      }
      if (localPosition_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LocalPosition);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BoneTypeValue != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BoneTypeValue);
      }
      if (BoneName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BoneName);
      }
      if (localRotation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(LocalRotation);
      }
      if (localPosition_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LocalPosition);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BoneTypeValue != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BoneTypeValue);
      }
      if (BoneName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BoneName);
      }
      if (localRotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LocalRotation);
      }
      if (localPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LocalPosition);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BoneTransform other) {
      if (other == null) {
        return;
      }
      if (other.BoneTypeValue != 0) {
        BoneTypeValue = other.BoneTypeValue;
      }
      if (other.BoneName.Length != 0) {
        BoneName = other.BoneName;
      }
      if (other.localRotation_ != null) {
        if (localRotation_ == null) {
          LocalRotation = new global::VioletSolver.Recorder.Rotation();
        }
        LocalRotation.MergeFrom(other.LocalRotation);
      }
      if (other.localPosition_ != null) {
        if (localPosition_ == null) {
          LocalPosition = new global::VioletSolver.Recorder.Position();
        }
        LocalPosition.MergeFrom(other.LocalPosition);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BoneTypeValue = input.ReadInt32();
            break;
          }
          case 18: {
            BoneName = input.ReadString();
            break;
          }
          case 26: {
            if (localRotation_ == null) {
              LocalRotation = new global::VioletSolver.Recorder.Rotation();
            }
            input.ReadMessage(LocalRotation);
            break;
          }
          case 34: {
            if (localPosition_ == null) {
              LocalPosition = new global::VioletSolver.Recorder.Position();
            }
            input.ReadMessage(LocalPosition);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BoneTypeValue = input.ReadInt32();
            break;
          }
          case 18: {
            BoneName = input.ReadString();
            break;
          }
          case 26: {
            if (localRotation_ == null) {
              LocalRotation = new global::VioletSolver.Recorder.Rotation();
            }
            input.ReadMessage(LocalRotation);
            break;
          }
          case 34: {
            if (localPosition_ == null) {
              LocalPosition = new global::VioletSolver.Recorder.Position();
            }
            input.ReadMessage(LocalPosition);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AvatarPose : pb::IMessage<AvatarPose>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AvatarPose> _parser = new pb::MessageParser<AvatarPose>(() => new AvatarPose());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AvatarPose> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VioletSolver.Recorder.AvatarAnimationLogReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvatarPose() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvatarPose(AvatarPose other) : this() {
      boneTransforms_ = other.boneTransforms_.Clone();
      blendshapes_ = other.blendshapes_ != null ? other.blendshapes_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvatarPose Clone() {
      return new AvatarPose(this);
    }

    /// <summary>Field number for the "bone_transforms" field.</summary>
    public const int BoneTransformsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::VioletSolver.Recorder.BoneTransform> _repeated_boneTransforms_codec
        = pb::FieldCodec.ForMessage(10, global::VioletSolver.Recorder.BoneTransform.Parser);
    private readonly pbc::RepeatedField<global::VioletSolver.Recorder.BoneTransform> boneTransforms_ = new pbc::RepeatedField<global::VioletSolver.Recorder.BoneTransform>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::VioletSolver.Recorder.BoneTransform> BoneTransforms {
      get { return boneTransforms_; }
    }

    /// <summary>Field number for the "blendshapes" field.</summary>
    public const int BlendshapesFieldNumber = 2;
    private global::VioletSolver.Recorder.Blendshapes blendshapes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::VioletSolver.Recorder.Blendshapes Blendshapes {
      get { return blendshapes_; }
      set {
        blendshapes_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AvatarPose);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AvatarPose other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!boneTransforms_.Equals(other.boneTransforms_)) return false;
      if (!object.Equals(Blendshapes, other.Blendshapes)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= boneTransforms_.GetHashCode();
      if (blendshapes_ != null) hash ^= Blendshapes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      boneTransforms_.WriteTo(output, _repeated_boneTransforms_codec);
      if (blendshapes_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Blendshapes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      boneTransforms_.WriteTo(ref output, _repeated_boneTransforms_codec);
      if (blendshapes_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Blendshapes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += boneTransforms_.CalculateSize(_repeated_boneTransforms_codec);
      if (blendshapes_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Blendshapes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AvatarPose other) {
      if (other == null) {
        return;
      }
      boneTransforms_.Add(other.boneTransforms_);
      if (other.blendshapes_ != null) {
        if (blendshapes_ == null) {
          Blendshapes = new global::VioletSolver.Recorder.Blendshapes();
        }
        Blendshapes.MergeFrom(other.Blendshapes);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            boneTransforms_.AddEntriesFrom(input, _repeated_boneTransforms_codec);
            break;
          }
          case 18: {
            if (blendshapes_ == null) {
              Blendshapes = new global::VioletSolver.Recorder.Blendshapes();
            }
            input.ReadMessage(Blendshapes);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            boneTransforms_.AddEntriesFrom(ref input, _repeated_boneTransforms_codec);
            break;
          }
          case 18: {
            if (blendshapes_ == null) {
              Blendshapes = new global::VioletSolver.Recorder.Blendshapes();
            }
            input.ReadMessage(Blendshapes);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Blendshapes : pb::IMessage<Blendshapes>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Blendshapes> _parser = new pb::MessageParser<Blendshapes>(() => new Blendshapes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Blendshapes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VioletSolver.Recorder.AvatarAnimationLogReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Blendshapes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Blendshapes(Blendshapes other) : this() {
      weights_ = other.weights_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Blendshapes Clone() {
      return new Blendshapes(this);
    }

    /// <summary>Field number for the "weights" field.</summary>
    public const int WeightsFieldNumber = 1;
    private static readonly pb::FieldCodec<float> _repeated_weights_codec
        = pb::FieldCodec.ForFloat(10);
    private readonly pbc::RepeatedField<float> weights_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Weights {
      get { return weights_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Blendshapes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Blendshapes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!weights_.Equals(other.weights_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= weights_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      weights_.WriteTo(output, _repeated_weights_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      weights_.WriteTo(ref output, _repeated_weights_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += weights_.CalculateSize(_repeated_weights_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Blendshapes other) {
      if (other == null) {
        return;
      }
      weights_.Add(other.weights_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 13: {
            weights_.AddEntriesFrom(input, _repeated_weights_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 13: {
            weights_.AddEntriesFrom(ref input, _repeated_weights_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Blendshapes message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum BlendshapesIndex {
        [pbr::OriginalName("_neutral")] Neutral = 0,
        [pbr::OriginalName("browDownLeft")] BrowDownLeft = 1,
        [pbr::OriginalName("browDownRight")] BrowDownRight = 2,
        [pbr::OriginalName("browInnerUp")] BrowInnerUp = 3,
        [pbr::OriginalName("browOuterUpLeft")] BrowOuterUpLeft = 4,
        [pbr::OriginalName("browOuterUpRight")] BrowOuterUpRight = 5,
        [pbr::OriginalName("cheekPuff")] CheekPuff = 6,
        [pbr::OriginalName("cheekSquintLeft")] CheekSquintLeft = 7,
        [pbr::OriginalName("cheekSquintRight")] CheekSquintRight = 8,
        [pbr::OriginalName("eyeBlinkLeft")] EyeBlinkLeft = 9,
        [pbr::OriginalName("eyeBlinkRight")] EyeBlinkRight = 10,
        [pbr::OriginalName("eyeLookDownLeft")] EyeLookDownLeft = 11,
        [pbr::OriginalName("eyeLookDownRight")] EyeLookDownRight = 12,
        [pbr::OriginalName("eyeLookInLeft")] EyeLookInLeft = 13,
        [pbr::OriginalName("eyeLookInRight")] EyeLookInRight = 14,
        [pbr::OriginalName("eyeLookOutLeft")] EyeLookOutLeft = 15,
        [pbr::OriginalName("eyeLookOutRight")] EyeLookOutRight = 16,
        [pbr::OriginalName("eyeLookUpLeft")] EyeLookUpLeft = 17,
        [pbr::OriginalName("eyeLookUpRight")] EyeLookUpRight = 18,
        [pbr::OriginalName("eyeSquintLeft")] EyeSquintLeft = 19,
        [pbr::OriginalName("eyeSquintRight")] EyeSquintRight = 20,
        [pbr::OriginalName("eyeWideLeft")] EyeWideLeft = 21,
        [pbr::OriginalName("eyeWideRight")] EyeWideRight = 22,
        [pbr::OriginalName("jawForward")] JawForward = 23,
        [pbr::OriginalName("jawLeft")] JawLeft = 24,
        [pbr::OriginalName("jawOpen")] JawOpen = 25,
        [pbr::OriginalName("jawRight")] JawRight = 26,
        [pbr::OriginalName("mouthClose")] MouthClose = 27,
        [pbr::OriginalName("mouthDimpleLeft")] MouthDimpleLeft = 28,
        [pbr::OriginalName("mouthDimpleRight")] MouthDimpleRight = 29,
        [pbr::OriginalName("mouthFrownLeft")] MouthFrownLeft = 30,
        [pbr::OriginalName("mouthFrownRight")] MouthFrownRight = 31,
        [pbr::OriginalName("mouthFunnel")] MouthFunnel = 32,
        [pbr::OriginalName("mouthLeft")] MouthLeft = 33,
        [pbr::OriginalName("mouthLowerDownLeft")] MouthLowerDownLeft = 34,
        [pbr::OriginalName("mouthLowerDownRight")] MouthLowerDownRight = 35,
        [pbr::OriginalName("mouthPressLeft")] MouthPressLeft = 36,
        [pbr::OriginalName("mouthPressRight")] MouthPressRight = 37,
        [pbr::OriginalName("mouthPucker")] MouthPucker = 38,
        [pbr::OriginalName("mouthRight")] MouthRight = 39,
        [pbr::OriginalName("mouthRollLower")] MouthRollLower = 40,
        [pbr::OriginalName("mouthRollUpper")] MouthRollUpper = 41,
        [pbr::OriginalName("mouthShrugLower")] MouthShrugLower = 42,
        [pbr::OriginalName("mouthShrugUpper")] MouthShrugUpper = 43,
        [pbr::OriginalName("mouthSmileLeft")] MouthSmileLeft = 44,
        [pbr::OriginalName("mouthSmileRight")] MouthSmileRight = 45,
        [pbr::OriginalName("mouthStretchLeft")] MouthStretchLeft = 46,
        [pbr::OriginalName("mouthStretchRight")] MouthStretchRight = 47,
        [pbr::OriginalName("mouthUpperUpLeft")] MouthUpperUpLeft = 48,
        [pbr::OriginalName("mouthUpperUpRight")] MouthUpperUpRight = 49,
        [pbr::OriginalName("noseSneerLeft")] NoseSneerLeft = 50,
        [pbr::OriginalName("noseSneerRight")] NoseSneerRight = 51,
        [pbr::OriginalName("tongueOut")] TongueOut = 52,
        [pbr::OriginalName("length")] Length = 53,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DeviceUsage : pb::IMessage<DeviceUsage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DeviceUsage> _parser = new pb::MessageParser<DeviceUsage>(() => new DeviceUsage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DeviceUsage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::VioletSolver.Recorder.AvatarAnimationLogReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceUsage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceUsage(DeviceUsage other) : this() {
      isMouseUsing_ = other.isMouseUsing_;
      isKeyboardUsing_ = other.isKeyboardUsing_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeviceUsage Clone() {
      return new DeviceUsage(this);
    }

    /// <summary>Field number for the "is_mouse_using" field.</summary>
    public const int IsMouseUsingFieldNumber = 1;
    private bool isMouseUsing_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsMouseUsing {
      get { return isMouseUsing_; }
      set {
        isMouseUsing_ = value;
      }
    }

    /// <summary>Field number for the "is_keyboard_using" field.</summary>
    public const int IsKeyboardUsingFieldNumber = 2;
    private bool isKeyboardUsing_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsKeyboardUsing {
      get { return isKeyboardUsing_; }
      set {
        isKeyboardUsing_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DeviceUsage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DeviceUsage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsMouseUsing != other.IsMouseUsing) return false;
      if (IsKeyboardUsing != other.IsKeyboardUsing) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IsMouseUsing != false) hash ^= IsMouseUsing.GetHashCode();
      if (IsKeyboardUsing != false) hash ^= IsKeyboardUsing.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IsMouseUsing != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsMouseUsing);
      }
      if (IsKeyboardUsing != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsKeyboardUsing);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IsMouseUsing != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsMouseUsing);
      }
      if (IsKeyboardUsing != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsKeyboardUsing);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IsMouseUsing != false) {
        size += 1 + 1;
      }
      if (IsKeyboardUsing != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DeviceUsage other) {
      if (other == null) {
        return;
      }
      if (other.IsMouseUsing != false) {
        IsMouseUsing = other.IsMouseUsing;
      }
      if (other.IsKeyboardUsing != false) {
        IsKeyboardUsing = other.IsKeyboardUsing;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IsMouseUsing = input.ReadBool();
            break;
          }
          case 16: {
            IsKeyboardUsing = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IsMouseUsing = input.ReadBool();
            break;
          }
          case 16: {
            IsKeyboardUsing = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
